# .gitpod.yml

tasks:
  - init: | # This runs once when the workspace is being built/prepared
      echo "Adding deadsnakes PPA and installing Python 3.13, pip, venv, dev tools, git, unzip..."
      sudo apt-get update -y
      # Install software-properties-common to get add-apt-repository
      sudo apt-get install -y software-properties-common
      # Add the deadsnakes PPA
      sudo add-apt-repository -y ppa:deadsnakes/ppa
      sudo apt-get update -y
      # Install Python 3.13 and associated packages, plus unzip
      sudo apt-get install -y python3.13 python3.13-pip python3.13-venv python3.13-dev git unzip
      
      echo "Installing uv using pip3.13..."
      # Install uv using the pip from our Python 3.13 installation
      # This makes uv available system-wide
      sudo pip3.13 install uv
      echo "Python 3.13 and uv installation attempt complete."
      
      echo "To use Python 3.13 for your project, consider creating a virtual environment:"
      echo "  python3.13 -m venv .venv"
      echo "  source .venv/bin/activate"
      echo "Or using uv to manage it:"
      echo "  uv venv"
      echo "  source .venv/bin/activate"


    command: | # This runs every time the workspace starts
      echo "Workspace is ready!"
      echo "----------------------------------------"
      echo "Available Python 3.13:"
      python3.13 --version
      echo "----------------------------------------"
      echo "Available pip for Python 3.13 (pip3.13):"
      pip3.13 --version
      echo "----------------------------------------"
      echo "Available uv:"
      uv --version
      echo "----------------------------------------"
      echo "Default python3 version (might be different if not explicitly changed):"
      python3 --version
      echo "----------------------------------------"

vscode:
  extensions:
    - ms-python.python # Microsoft Python extension
    - astral-sh.uv # Official Astral extension for uv (recommended)